[package]
name = "liftbridge-examples"
version = "0.1.0"
authors = ["Roman Useinov <roman.useinov@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
liftbridge = "0.1.0"
actix-rt = "1.1.1"
